### ISSUE TITLE
네비게이션 드로워 API 문서를 보면서 사용법 익히기

### ISSUE THREAD

**Issue by baramofme** [nmj8585/Vue-sr#3]
컴포넌트 문서 하나하나 옵션을 건드리고 실제 소스에 적용하면서 익히기

https://v2.vuetifyjs.com/ko/components/navigation-drawers/

```
      <v-navigation-drawer
        v-model="drawer"
        app
      >
```

위 태그를 보면, app 이라는 속성과 value 라는 속성을 사용함

app props 의 경우에는. 기본 값이 false. 

설명은 컨텐츠 사이즈를 동적으로 조절하는데 쓴다고 나옴. 이건 뷰티파이 레이아웃 기능이 정상 작동하기 위해 필요한 속성

![image](https://user-images.githubusercontent.com/44565599/114349359-c100e280-9ba2-11eb-8664-4ed4c8c89d87.png)

```
      <v-navigation-drawer
        v-model="drawer"
        :app="false"
      >
```

```
      <v-navigation-drawer
        v-model="drawer"
        :app="true"
      >
```

값을 생략하고 속성명만 적으면 true 값을 준 거다.

```
      <v-navigation-drawer
        v-model="drawer"
        app
      >
```

아예 속성명도 안 적으면, props 기본 값이 false 라서 컴포넌트 내부에서 false 로 값이 설정됨

```
      <v-navigation-drawer
        v-model="drawer"
      >
```

v-model="drawser" 는 속성이 뭔지 모르겠을 거임. 속성은 value.

아래 설명을 보면 보여지고 숨기는 것을 결정한다고 되어있음.

![image](https://user-images.githubusercontent.com/44565599/114349736-41274800-9ba3-11eb-80a2-ee98ce65a16e.png)

```
      <v-navigation-drawer
        :value="true"
        app
      >
```

```
      <v-navigation-drawer
        :value="false"
        app
      >
```

v-model 은 양방향, value 는 단방향 바인딩.

차이는 아래 문서를 보면서 공부할 것.

https://joshua1988.github.io/web-development/vuejs/v-model-usage/

**Comment by nmj8585** [comment]
상황1 
난감했다... 
이슈 자체를 이해 보다 옵션을 건들여 보라고 적혀 있어서 여러 사이트를 검색해봤는데
상냥하게 뭐가 무엇 인지 나온게 하나두 없었다 
기능적으로 어떻해 뭐고 뭐라는게 전혀 없는 상황 이였음 
컴포넌트 api 오버뷰 를 위에 해당 테그를 입력해서 보면  설명 조금이랑
설명 창에 카테고리 이벤트 프롭스를 눌러도 무엇을 말하는지 알수없는 상황이 발생이되었다.
그래서 일단은 가장 기본적인 테그가 가지고 있는 기능 과 사용법을 보기로 했다.

그전에 vuetify 는 화면 ui를 구성하는 프레임 워크이고 vue에서 
당현히 사용하기 최적화된 부트스트렙과 유사한 
구글 머트감했다... 
이슈 자체를 이해 보다 옵션을 건들여 보라고 적혀 있어서 여러 사이트를 검색해봤는데
상냥하게 뭐가 무엇 인지 나온게 하나두 없었다 
기능적으로 어떻해 뭐고 뭐라는게 전혀 없는 상황 이였음 
컴포넌트 api 오버뷰 를 위에 해당 테그를 입력해서 보면  설명 조금이랑
설명 창에 카테고리 이벤트 프롭스를 눌러도 무엇을 말하는지 알수없는 상황이 발생이되었다.
그래서 일단은 가장 기본적인 테그가 가지고 있는 기능 과 사용법을 보기로 했다.

그전에 vuetify 는 화면 ui를 구성하는 프레임 워크이고 vue에서 
당현히 사용하기 최적화된 부트스트렙과 유사한 
구글 머티리얼 디자인을 바탕으로 만들었다고한다 
(구글에서 많이사용하는 디자인방식을 따왔으니 완성도랑 사용성이좋겠지
추정한다.) 

각각 테그는 미리 만들어진 내장객체 처럼 복붙하면 
기본 저장된 기능이 사용 되는 방식이고  
클레스나 속성명 변경에 따른 색상 크기 생성 위치를 지정해줄수 있는걸로
보인다
일단 크기에 대한건

커스터 마이징 > Breakpoints 에서 확인 
기본은  boolean 에 false 로 되여있고 

화면에 출력되는 크기에 따라서 아래의 정의 된 
디폴트(기본크기값)  xs 는 크기가 < 600px 일때   
크기로 컨텐츠크기가 변경되여 보여지는 반응형이라 보면 된다.

이런식으로 공식 홈피를 보면 되는데 역시나.. 상냥하지 않아서

**Comment by baramofme** [comment]
속성 하나하나를 알려줄 사람은 없음. 영어를 내가 해석하고 자꾸 이게 무슨 연관이 있는 지 잔머리를 굴려야 함.

그러나 기본 보는 방식에 대해서는 아래 예시를 준비.

## **기본내용.**

<태그 속성=값 />

<v-navigation-drawer  :value="drawer" :app="false" >

v-natigation 이라는 태그의 value, app 속성이 있고,

value 속성에는 drawer 라는 변수를 바인딩하고.

app  에는 false 라는 자바스크립트 불린 값을 할당한다.

태그로는 속성인데, vue-js 컴포넌트로는 props. 

(prop 가 뭔지, 그걸 어떻게 쓰는 지는 공부하시오)


## **props 활용**

### color(색깔) prop

![image](https://user-images.githubusercontent.com/44565599/114395645-98dfa680-9bd7-11eb-93fe-ba2ab7178156.png)

type(종류) string(문자열)
default(기본값) undefined

머터리얼 색깔 "success", "purple" 이나 css 색 코드 "#033" , "rgba(255, 0, 0, 0.5))" 을 값으로 넣으면 해당 색을 컴포넌트에 적용한다.

<v-navigation-drawer  color="purple" >

### expand-on-hover(마우스위로 호버시 확장) prop

![image](https://user-images.githubusercontent.com/44565599/114396084-1a373900-9bd8-11eb-9524-c050827eca34.png)

type(종류) boolean(참거짓)
default(기본값) false

마우스로 위로 호버할 때까지 미니 모드로 접어둔다.

<v-navigation-drawer  :expand-on-hover="true" >

### right(오른쪽으로 위치시키기) prop

![image](https://user-images.githubusercontent.com/44565599/114396084-1a373900-9bd8-11eb-9524-c050827eca34.png)

type(종류) boolean(참거짓)
default(기본값) false

탐색 서랍을 기본이 왼쪽인데, 오른쪽에 위치시킴

<v-navigation-drawer  :expand-on-hover="true" >

**Comment by baramofme** [comment]
@nmj8585 

위 기본 문서 보는 방법을 보고, 이해가 간다면.

각 props 를 현재 작성된 v-navigation-drawer 에 적용하고 저장 하면서, 어떻게 모양이 바뀌는 지 확인해보기.
- [x] 위 세 가지 예시 속성마다 값을 달리해서 컴포넌트 변화 확인
- [x] height 속성을 조절해서 높이를 변화 확인
- [ ] light 속성, 이하 동일
- [ ] value 속성,( 보이거나 숨기기)

**Comment by nmj8585** [comment]
이걸 공부하면서 느낀건 vue 사용하는거랑 비슷하다고 해야하나 
거의 같기때문에 vue 공부하는거랑 같은 기분 ??

어제 알려준걸 복습해보자면  

```
<v-navigation-drawer
        v-model="drawer"
        app color="purple lighten-3"
      >
```
(내가 변경한 코드였음)

의 테그는 vuetify 라는 프레임 워크에 생성이되여있는 
컴포넌트 이고 
(컴포넌트 라는걸 알수있는 포인트는 
스크립트 단에 등록해놓은 (임포트그런거 떠나서) 컴포넌트를
템플릿 단에서 사용하려면 
<템플릿>

<div id="app">
 <v-navigation-drawer
        :value
        app
      >
 </v-navigation-drawer>
<div/>
<스크립트> 
export default {
components: {
   vNavigationDrawer,
 }
}
위처럼 등록을 시켜서 사용할수 있는점이고 여기에서 의문은

1.템플릿 단 등록 컴포넌트 명이랑 스크립트단 등록명이 다른이유

열심히 검색하고 찾아보고한 결과 
그것은 vue 공식 스타일가이드에 나와 있는 작성법에 따른 것이고 
스타일가이드에 나온 방식으로 작성을 하면 vue에서 자동으로 
인식을 한다는것 !!

좀더 자세하게 적자면  찾으면서도 신기했음

1)HTML에서는 대소문자를 구별을 못함 (이부분이 핵심)
2) 그래서 스크립트영역에 작성할경우 권고 하는 
카멜형식: appNmj 로 작성을 하고 
3)템플릿 단에서 케밥형식: app-nmj으로 작성해도 vue에서
자동으로 같은컴포넌트로 인식해줘서 이런일이 발생됨 

결국 HTML에서 대소문을 인식을 못하니 많은 컴포넌트
가 사용이될경우 생성시 구별 및 어려움이 있어서
vue의 템플릿 단에서는 2단어이상의 단어가 조합된 경우라는
상황을 둬서 사용이나 구별하기 용이하게해서 쓰는걸로 알수있음

2. 위 컴포넌트를 보면 마치  HTML에 attribute(속성) 인지 무엇인지 
알수가 없음 

일단 HTML의 경우 테그 레퍼런스 를 보면 가능하긴 하나 
이경우는  아래 원본 코드를 보면 

<v-navigation-drawer
        v-model="drawer"
        app
      >
1)일단 당연히 위 테그는 HTML테그가 아니다 (위 1번 의문에 적혀있음)
2)v-model이라는 디렉티브를 사용하여 drawer이라는  값을 잡고있다 

나머지는 잠시 외출하고 더 이해해보기위에  기록...


(스스로에게 설명하기위한 기록임 )

**Comment by nmj8585** [comment]
color(색깔) prop
![K-002](https://user-images.githubusercontent.com/21999965/114697358-c869ec80-9d58-11eb-9f66-924395d64d67.jpg)
![K-003](https://user-images.githubusercontent.com/21999965/114697371-cc960a00-9d58-11eb-9553-a78fb4fbe5c8.jpg)
![K-004](https://user-images.githubusercontent.com/21999965/114697389-d0299100-9d58-11eb-93d6-ec1da676000d.jpg)
1.칼라(머테리얼)
2.css 색상표 
3.rgba (변환해주는게 있어서 의미색상 만들어서 넣어봄)

expand-on-hover(마우스위로 호버시 확장) prop
![K-005](https://user-images.githubusercontent.com/21999965/114699024-b8eba300-9d5a-11eb-9d8e-abfd3a5fa97e.jpg)

전에는 넒적하기만 했는데 적용하면 마우스가 
근처에 가기전까지는 작아졌다가 다가가면 원래본 크기로 
나옴 

right(오른쪽으로 위치시키기) prop
![K-006](https://user-images.githubusercontent.com/21999965/114699457-4dee9c00-9d5b-11eb-864d-28687f827bcf.jpg)

넣자마자 바로 옴겨가는걸 볼수있음

**Comment by nmj8585** [comment]
height (높이조절) prop
![K-001](https://user-images.githubusercontent.com/21999965/114700443-79be5180-9d5c-11eb-8f57-d825eebbbf80.jpg)

기종작성한 위 라이트상황에서 의 컨텐츠 길이를 보면 
변화된것을 알수있다.

light (밝은 테마 변형을 구성 요소에 적용) prop 

![K-003](https://user-images.githubusercontent.com/21999965/114702299-dd497e80-9d5e-11eb-8450-8c69ab247ed5.jpg)

당황스러운 속성...
변화를 찾을수가 없다 

1.색상의 문제가 있는것 같아서 변경 함 
2.값기입 오류인가 싶어서 트루, 다크 , 값없이 일반 으로넣어두 변화가 않보임

당황스럽다.

value(구성 요소의 표시 여부를 제어) 

![K-004](https://user-images.githubusercontent.com/21999965/114704134-31edf900-9d61-11eb-9a87-39fb9a1a1710.jpg)

아주 당황스럽다 벨류에 펄스를 넣으면  작동을 안하거나 그럴줄 알았는데
전혀 ....;;;;;;;;;

**Comment by nmj8585** [comment]
일단 변화가 눈에 보였다는건 좋았음 귯

**Comment by baramofme** [comment]
@nmj8585 

value="false" 랑 :value="false" 랑 무슨 차이가 있는지?

**Comment by nmj8585** [comment]
![K-002](https://user-images.githubusercontent.com/21999965/114708756-bdb65400-9d66-11eb-823c-772a14ad2088.jpg)

눈에 뛸정도의 변화 나 기존이랑 변화는 없었음

**Comment by baramofme** [comment]
@nmj8585 문법적으로.

vue-js 데이터 바인딩에 대해서 알고 있으면 대답을 위처럼 할 수 없음.

해보기 value="false" 와  :value="true"
해보기 value="true" 와  :value="true"

위게 거 해본 뒤에 value="false" 혹은 value="true" 하는 것과 v-bind:value="false" 혹은 v-bind:value="true" 하는 것의 차이를  value 라는 props 를 통해 내부에서 값을 받는 컴포넌트 입장에서 글로 서술하시오.

**Comment by nmj8585** [comment]
일단 위에 경우에 수는 위에 스샷과 동일 함 
로컬로 돌려봤을땐 변화 없었음 
1.벨류의 값을  잘못 기입한건지  혹은 그 값이 아닌지 모르겠음 

```
<v-navigation-drawer
      height="50%
       value="false" 
      >
```
위에 v-네비게이션이라는 컴포넌트에 하위 컴포넌트인 하이라이트(높이)를
props로 올려서 사용한다는 의미 이고 
 변경하지 않거나 기입만 해놨을때는 기본 값 (디폴트: false로 변화 없음)
값을 주지 않았기에 기본 생성으로 되고  값을 주는 순간 그거에 마춰서 
영향을 주는걸로 아는데 
저기 벨류의 값은  어떤용도의 어떤 효과를 주기위에 사용하는지 
이해를 못하겠음...ㅠ
