### ISSUE TITLE
v-model 과 :value 의 차이를 공부하고 실습해보시오.

### ISSUE THREAD

**Issue by baramofme** [nmj8585/Vue-sr#4]
https://jsfiddle.net/381510688/uyppvvL0/

**Comment by baramofme** [comment]
@nmj8585 실습 하고 있나요. 친구?

**Comment by baramofme** [comment]
@nmj8585 친구. 나 열심히 하고 있어. 친구도 힘내고 있지? 

나 혼자만 하는 거 아니라고 믿는다.

내가 원한 건 아래 코드였음.  v-model 이랑 value 차이

https://jsfiddle.net/671z92j5/

**Comment by nmj8585** [comment]
```
  <p>데이터 변수 name {{name}}</p>
    <input type="text" :value="name">
    <p>
    value 는 데이터 -> html 로만 변경 단방향 전파
    </p>

``` 
타입 텍스트 와 벨류의 값으로 네임이라는  속성을가진
HTML 인풋테그

```
data() {
    return {
      name: 'lg',
      age: 27,
      address: ''
    }
```
스크립트 단  데이터 객체 내에 
리턴에 객체로 네임,에이지,어드레스에 각각 값을 넣어주고 

위에  생성한 HTML의 인픗테그 속성  벨류="네임" 에
vue의 디렉티브 중 v-bind 를 사용 데이터 바인딩이된 
값을 인풋에 출력을 하려고 함 

```
 components: {
    'child-component': {
      props: ['value'],
      template: `
      <div>
        <input v-bind:value="value"
               @input="updateValue($event.target.value)">
        </input>
      </div>
      `,
      methods: {
        updateValue(value) {
          this.$emit('input', value);
        
```
최상위 컴포넌트인 이름이 app 라는것이고 
컴포넌츠에  차일드 컴포넌트라는건 추상하기로는 하위컴포넌트라는것


벨류라는 이름의 객체의 값을 하위컴포넌트로 전달하기위해 
데이터바인딩이 된   프롭스 에 벨류 라는 프롭스 속성명을 넣고 

위 최상위에 등록된  



메서드의 
함수 업데이트벨류의 매개변수로 벨류 라는 이름의 데이터가 
들어올시   인풋 과 벨류의 값이 
 this.$emit 로 상위 컴포넌트로 다시 올라가서 출력된다.

**Comment by nmj8585** [comment]
![K-001](https://user-images.githubusercontent.com/21999965/114679339-0827d880-9d47-11eb-9083-5b6209f41b59.jpg)
난감하내.. 왜 위에 세이브가 않되는거야 ㅡㅡ 돌겠..
