### ISSUE TITLE
기존 사이트 구조 파악

### ISSUE THREAD

**Issue by baramofme** [nmj8585/Vue-sr#6]
@nmj8585 다음 숙제~

소니 엔젤 사이트는 현재 반응형이다.
즉, 넓이에 따라서 내부 모양이 바뀜.

그럼 구체적으로 어떻게 바뀌는 지를 파악해보자.

**Comment by baramofme** [comment]
1. 각 HTML 태그 부분이 화면에 어느 부분과 연결되는 지 캡처하고 적어보시오.

![image](https://user-images.githubusercontent.com/44565599/114699589-77a7c300-9d5b-11eb-92c1-0d9fdc8501c3.png)

확인할 태그부분

`<div id="header" style="height: auto;"></div>`
`<div id="wrap"></div>`
`<div id="sidebar-wrapper"></div>`
`<div id="myshop-wrapper"></div>`
`<div id="footer"></div>`


예) `<div id="myshop-wrapper">..</div>` 는 화면이 작아졌을 때 나오는 사이드 네비게이션부분이다.

![image](https://user-images.githubusercontent.com/44565599/114699666-9017dd80-9d5b-11eb-9c1f-14910c5f6354.png)

**Comment by baramofme** [comment]
2. 각 부분이 화면 넓이에 따라서 어떻게 변하는 지 확인하고 캡쳐 해보시오.
넓이 px 확인하려면 개발자 도구 창 켜놓고 화면을 줄였다 넓히면 됨

확인할 태그부분

`<div id="header" style="height: auto;"></div>`
`<div id="wrap"></div>`
`<div id="sidebar-wrapper"></div>`
`<div id="myshop-wrapper"></div>`
`<div id="footer"></div>`

예시

### `<div id="footer"></div>` 부분

1100px 이상 : 좌측 로고 및 정보. 오른쪽은 메뉴들 

![image](https://user-images.githubusercontent.com/44565599/114700284-4e3b6700-9d5c-11eb-8b9b-2b3edea5627e.png)


1100px 미만:  로고 부분이 아래쪽으로 이동. 왼쪽 메뉴 부분은 넓이를 100% 차지.

![image](https://user-images.githubusercontent.com/44565599/114700432-762aca80-9d5c-11eb-9449-106af67cd874.png)

**Comment by nmj8585** [comment]
```
<div id="header" style="height: auto;"></div>
```
![K-002](https://user-images.githubusercontent.com/21999965/114705726-02d88700-9d63-11eb-9763-d496bf333678.jpg)

헤더는 웹 페이지 상의  상단에 위치해  있으며 

![K-001](https://user-images.githubusercontent.com/21999965/114707802-99a64300-9d65-11eb-888c-12154f30aef0.jpg)

너비가 980px보다 작아질시 
1. 타이틀이 큰중앙에서  죄측 버거버튼 옆으로 이동
2. 페이스북 및 인스타그램 링크버튼이 사라짐 
3. 메인타이틀 아래 각종메뉴들도 사라짐

여기에서 재미있는 부분은 너비에 따라 헤더가 작아질수록 변신로봇처럼 변한다
1296의 경우다 
![K-008](https://user-images.githubusercontent.com/21999965/114827498-babd7100-9e03-11eb-9e83-076e554609da.jpg)
1.2 좌우 페딩중 우측 이 커짐
3.위 메뉴중 1메뉴 내려옴

1113의경우
![K-009](https://user-images.githubusercontent.com/21999965/114827676-f8ba9500-9e03-11eb-9300-9a2348f1559e.jpg)
1.우측 패딩만 있음
2.메뉴 1개 내려옴


1159의 경우
![K-011](https://user-images.githubusercontent.com/21999965/114827864-29023380-9e04-11eb-8ddd-d3132cc7dfce.jpg)
1.최소한의 좌우 페딩만 생김
2. 추정이나 메뉴 폰트 사이즈가 작아보임
3. 메뉴가 다시 올라감

989의경우
![K-010](https://user-images.githubusercontent.com/21999965/114828045-66ff5780-9e04-11eb-9bd5-a22ba5381b02.jpg)
1.우측패딩만 남아 있고 (위 1113의 경우와 흡사함)
2.위 메뉴 2개가 내려온 모습

마지막 980 이하
![K-012](https://user-images.githubusercontent.com/21999965/114828163-8a2a0700-9e04-11eb-9cfe-9953f14f2db3.jpg)
위 에서 보았던 반응형으로 완전 변경된 모습

**Comment by nmj8585** [comment]
```
<div id="wrap"></div>
```
![K-001](https://user-images.githubusercontent.com/21999965/114749072-81e2b500-9d8d-11eb-8b44-9dfc81b310a7.jpg)
이 부위는 바디 혹은 컨텐츠 이면서 스크롤을 길게길게 내리면서 상품홍보를 위한 곳이다

![K-002](https://user-images.githubusercontent.com/21999965/114753989-08e65c00-9d93-11eb-9e26-400869eeba92.jpg)

너비가 작아지면 컨텐츠의 정렬이 달라지는데 우선 풀 사이즈 화면의 정렬이다.

![SNAG-0001](https://user-images.githubusercontent.com/21999965/114753789-d76d9080-9d92-11eb-8475-b614c04a5198.jpg)

큰변화없는 최상단 베너는 동일 그아래부터 보면 
풀사이즈 
1. bast wish = 5
2. 121 배치 배너 
3. 가로 중간 베너 
4.sonny Angel Regular  = 4 
5. 자동 이동베너 = 3
6. 카드형식배너 = 6
7. 마지막 미니베너 = 22 
의 배치로 이루워 지고 있고 


이것도 위에서 처럼  창의 크기가 줄어들었을때 상품 리스트의 곗수변화가
심하다..
* < 의 경우 기존에서 변경 사항

1368의 경우 
1. bast wish = 5
2. 121 배치 배너 
3. 가로 중간 베너 
4.sonny Angel Regular  = 3 *
5. 자동 이동베너 = 3
6. 카드형식배너 = 6
7. 마지막 미니베너 = 14 * (우측에 잘린흔적은보임)

1187의 경우 
1. bast wish = 4 *
2. 121 배치 배너 
3. 가로 중간 베너 
4.sonny Angel Regular  = 3 
5. 자동 이동베너 = 1 * (가운데 것만 기존 크기고 나머지는 짤려있음)
6. 카드형식배너 = 6
7. 마지막 미니베너 = 14 

980의 경우
1. bast wish = 3 *
2. 121 배치 배너 
3. 가로 중간 베너 
4.sonny Angel Regular  = 3 
5. 자동 이동베너 = 1 (완벽한 1개)
6. 카드형식배너 = 6
7. 마지막 미니베너 = 10 *

480의 경우 
1. bast wish = 3 
2. 121 배치 배너 
3. 가로 중간 베너 
4.sonny Angel Regular  = 2 * 
5. 자동 이동베너 = 1 
6. 카드형식배너 = 6
7. 마지막 미니베너 = 4 *

순으로 변동이 되었다.

**Comment by nmj8585** [comment]
```
<div id="sidebar-wrapper"></div>
```
일단 이건 설명좀 들어봐야할 듯함 
사이드바  관련이라 확인해보니 우측 스크롤을 움직이면
무언가 표시는되는데 표시관련헤서 무슨역활인지 모르겠음...

**Comment by nmj8585** [comment]
```
<div id="myshop-wrapper"></div>
```
![K-001](https://user-images.githubusercontent.com/21999965/114840988-55bd4780-9e12-11eb-8995-da4fe6b9685f.jpg)

위 영수가 스샷을 올렸지만 조금 더 추가 하자면 
![K-003](https://user-images.githubusercontent.com/21999965/114843461-cf563500-9e14-11eb-9ba8-f5dc7b82ba5a.jpg)
이 부분은 980이하일때 즉 헤더부분이 변경이 일어나고 버거 버튼이 생성이 됬을때 클릭을해야 볼수있는 부분

![K-002](https://user-images.githubusercontent.com/21999965/114843618-f7459880-9e14-11eb-8592-ded42ec406a8.jpg)

980일때 메뉴가 사라지고 버거버튼을 클릭해야 사이드바가 옆으로 나오면서
로그인 및  회원가입 
 검색 및 메뉴 칸이 카테고리로 묶여서 볼수 있다.

**Comment by nmj8585** [comment]
```
<div id="footer"></div>
```
![K-004](https://user-images.githubusercontent.com/21999965/114995126-76e86b80-9ed8-11eb-846d-89bb8830c974.jpg)

웹페이지의 최하단 에 위치한 푸터 
![K-005](https://user-images.githubusercontent.com/21999965/114995397-bd3dca80-9ed8-11eb-9860-2d17637b13c3.jpg)
980이하로 변했을때 배치가 좀 달라지긴하나 큰틀에서는 변화가 없다고 봐야한다

기존 맴버십  옆으로 메뉴는 고정이고

타이틀 기준으로 2열이 였던것이 

번호랑 관련 메뉴들이 상단으로 올라가고  

타이틀이랑 주소가  최하단으로 와서 나열된걸을 확인할수 있다.
