### ISSUE TITLE
현재 프로젝트 화면과 소니엔젤 사이트와의 차이점 파악

### ISSUE THREAD

**Issue by baramofme** [nmj8585/Vue-sr#8]
@nmj8585 소니엔젤처럼 현재 레이아웃을 수정해야 하니까. 차이점 파악 필요.
바빠서 접속을 못하고 있었어. 

1. 헤더

2. 사이드 메뉴

3. 푸터
예) 소니엔젤은 푸터가 본문 아래에 위치에 있고 스크롤을 해야만 보임
     현재 레이아웃은 푸터가 본문과 별도로 스크롤 없이도 화면 아래에 고정됨

**Comment by nmj8585** [comment]
메인홈 

1.헤더 
구성:

1)첫번줄 - 메인타이틀 및 링크 아이콘
2)두번줄 - 메뉴링크 

1-1-1 타이틀  
기능: 클릭시 메인홈 연결 
          마우스 호버시 색상변화 (핑크 > 회색)

타이틀이 이미지 파일임 
사용가능: Hover:  v-hover

1-1-2 링크아이콘
기능:  아이콘 클릭시 각각 연결된 사이트 및  기능으로 연결됨.

페이스북,인스타그램, *C/S페이지* , *회원가입* , *장바구니* , 찾기(검색)

회원가입 및 장바구니
기능: 마우스 호버시  각각에 카드가 나와서 확인가능 

사용가능: Icons: v-icon ,Cards:  v-card
추가구현: 
1)회원가입
2)장바구니

찾기(검색)
기능 클릭했을시 입력할수있게 커서 및 인기검색어가 보임
문구입력 X   엔터 키 입력시 모달창 :검색어를 입력해주세요 뜸

문구입력 O  *상품검색* 페이지 이동 

사용가능:  


아이콘들 
추가구현 
1)메티리얼 디자인 아이콘에 위 나열된 아이콘 확인
2)아이콘이 없을시 다른사이트 찾기 
3) 각각 링크 시켜 줘야함 

회원가입 및 장바구니
1) v-card 가 아닐시  구현사항 확인

찾기(검색)
1) 일반 모달창 으로 뜸.


1-2 메뉴링크 
기능: 각각 메뉴 를 누를시 상품 및 기타 페이지로 연결 
마우스 호버시 메뉴에 밑줄 생성 
상품페이지의경우 미리보기 상품카테고리  및 사진1 링크됨 

상품페이지
Regular Refine , Limited Edition , Artist Collection
Collaboration , Dreams Figures , 

Mask Refresh Kit

홍보 및 안내 
NEWS & EVENT , Membembership , Where to buy

사용가능 :  Tabs:  v-tabs-items
추가구현 :  
1)미리보기 사진 안나옴
2)각각 텍스트도 상품시즌관련 카테고리라서 링크요함 


반응형 (기본 980)
구성
1) 버거버튼 타이틀 및 기존 아이콘링크

1-1-1 타이틀 
기능: 클릭시 메인홈 연결 
          버거버튼 클릭시 

타이틀이 이미지 파일

1-2-1 버거버튼
기능: 버튼에 마우스 호버시 버튼모양 변함 (버거 > 화살표)
클릭시 좌측사이드에서  메뉴들이 나옴 

순서대로 
회원가입 , 찾기(검색) , 묶음아이콘(관심상품 , 마이페이지 , 주문조회)
카테고리(상품) , 뉴스&이벤트 , 멤버쉽 ,  힐투바이 (구입가능처 지도)
입급안내

추가구현: 위는 따로 구현을 찾아봐야할것 같음


1-2-2 기존 아이콘링크
기능: 기존 위의 링크와 동일하다 
C/S , 회원가입 , 장바구니 , 찾기(검색) 만 넣어주면됨


2.사이드 메뉴 
구성: 사이드바(스크롤) 조작시 생기는 변화 (이벤트)
기능:
1)사이드바 조작시 헤더 1-2- 링크 아이콘 변화 및 스크롤 따라다님 
2) 스크롤바 하단에 위아래 화살표 아이콘 생성  및 클릭시 
최상단 (헤더) , 최하단(푸터) 빠른이동

사용가능: v-virtual-scroll
추가기능:  

2-1-1 헤더 1-2 링크아이콘변화
기능: 스크롤 바를 헤더 구성 2)메뉴링크 보다 아래로 내려갈시
아래 메뉴들이 재배치 되면서 메뉴링크의 패딩변화와 텍스크 크기변화가
발생됨

타이틀 ,  Regular Refine , Limited Edition , Artist Collection ,
Collaboration , Dreams Figures , Mask Refresh Kit
NEWS & EVENT , Membembership , Where to buy

C/S , 회원가입 , 장바구니 , 찾기(검색)

위 메뉴 및 아이콘은 기존대로 들어감 

사용가능:
추가기능: 


2-1-2 스크롤 따라댕김(붙잡기?)
기능: 위 변화된 헤더 구성 2)메뉴링크 가 스크롤바를 
위아래 이동시 최상단에 고정되여 같이 움직임 
위에서 언급한 스크롤 바를 헤더 구성 2)메뉴링크 보다 위로가면 
기존 형태로 변환되고 이동 안됨

사용가능:
추가기능:

2-2-1 빠른이동 화살표 아이콘 생성 
기능: 스크롤바를 헤더 구성 2)메뉴링크 위치 보다 아래로 
내릴시 기존 부터위치에 아이콘이 생성됨 .

사용가능:
추가기능: 이것 역시 아이콘을 찾아봐야함 

2-2-2 빠른이동 아이콘 따라다님
기능: 위 1-2의 처럼 변화되면 생성이 되고 스크롤이동에따라 
같이 따라디니면서 붙어 있음 

차이점의 경우 최하단 푸터 위치 까지 와도 사라지지않고 그대로 
생성되여 있음

사용가능:
추가기능:

2-2-3 상하단 빠른이동
기능: 위  2-1- 빠른이동화살표 생성으로 클릭시
방향에 맞게 빠르게 스크롤바가  자동이동됨
약간 엘리베이터 처럼 움직인다 생각하면 편함

사용가능:
추가기능:


반응형 (기본 980)
이건 크기 상관없이 동일하게 동작함.


3.컨텐츠(메인)
구성: 헤더 아래부분부터 푸터 전까지 보이는 부위가 
컨텐츠에 해당 하는 부분이고  전체 창일경우의 보이는건

풀사이즈 기준

1)메인베너= 1
2)bast wish = 5
3)121 배치 배너
4)가로 중간 베너
5)sonny Angel Regular = 4
6)자동 이동베너 = 3
7)카드형식배너 = 6
8)마지막 미니베너 = 22

순이고 각 각 살펴 보자 

3-1 메인베너 
기능:  이미지 파일로 제품홍보를 위한 칸 
총 7장으로 구성되며  1장 씩 보여짐 
1)일정초 지난후 자동넥스트 진행 됨 
2)마우스 베너에 올릴시  투명아이콘 <Prev(이전)  , Next(다음)> 이 생성
3) 점 아이콘으로 클릭시 지정된 이미지 보여짐 
위 점아이콘으로 호버시 2) 투명아이콘 생성됨

3-1-1-1 메인베너 생성  

사용가능:
추가기능


3-1-1-2 일정시간 자동넥스트 

사용가능:
추가기능:

3-1-2-1 투명아이콘 생성 

사용기능:
추가기능:

3-1-2-2 이전 다음 기능 구현

사용가능:
추가기능:

3-1-3-1 점아이콘  생성  

사용가능:
추가기능:

3-1-3-2  점아이콘 호버  색상변경 (회색 > 검정)

사용기능:
추가기능:

3-1-3-3  점아이콘 클릭시 아이콘길이 및  지정 이미지로 변경  구현

사용기능:
추가기능:

3-1-3-4  점아이콘 호버 시  1-1-2-1 투명아이콘 생성 

사용기능:
추가기능:

3-2 bast wish = 5
구성:   bast wish 라는 소제목과  5개의 품목을 소개
총3단계로 구성됨 
1)미니 타이틀 
2)상품 소개 
3) 상품이동 

3-2-1 미니타이틀 (추천상품)
기능: 고객들이 장바구니에 많이 넣어둔 상품 모움  추정

사용가능:
추가기능:
타이틀은 폰트로 되여 있고 폰트의 색상도 정해져있다.
다만 회색의 선이 있는데 이건 구현방법 찾아봐야할듯

3-2-2 상품소개 
기능: 위에 넣어둔 베스트 10상품으로 나열 (추정)
1) 카드형식의 상품이 이름 및 가격이 보임  
2) 마우스 호버시 해당상품의 이미지가 다른이미지로 보이면서
미리보기 아이콘이 뜸  및 클릭시 상품 상세페이지 
2-1)미리보기 아이템 클릭시 팝업창으로 상품 상세내역이 보임 
3) 일정시간시 상품나열이 변경됨 베스트 10으로 추정되여 
우축에서 좌측으로 빠르게 지나감


3-2-2-1 카드형식 상품 소개
구성: 상품 이미지 및 종류 이름 가격 순으로 나열되여있음 

사용가능: Cards:  v-card 
추가기능: 

3-2-2-2 이미지 호버시 지정된 이미지로 보여짐 

사용가능:
추가기능:

3-2-2-2-1  이미지 호버시  미리보기 창 생성

사용가능:
추가기능:

3-2-2-2-2 이미지 클릭시 상품상세페이지로 이동

사용가능:
추가기능:

3-2-2-2-3  위에 미리보기 창 클릭시  창모드식(팝업식) 상품상세페이지 블러오기

사용가능:
추가기능:

3-2-2-3 상품 자동 변경 
기능: 위 메인베너 처럼 총 10개의 상품이 5개씩 일정시간뒤
우측에서 좌측으로 바르게 넘어가는 표현

사용가능:
추가기능:

3-2-3  상품 이동     
구성: 총 4개의 아이콘으로 구성됨 
각각 클릭시 좌 우에 지정된 상품들로 나열 
기본조건  어느것을 눌러도 그에 맞게 상품이 이동됨 

3-2-3-1 아이콘 생성
기능: 위에 나열된 4개의 모양에 맞는 아이콘 생성
사용가능:
추가기능:

3-2-3-2 아이콘 클릭시 상품이동 1 원 아이콘 
기능 위 3-2-2-3 상품 자동 변경에 마춰서 자동변경이 일어난 시점에서
아이콘색상으로 변경됨을 알려줌(회색 > 검정)

사용가능:
추가기능: 그안에 동그란 아이콘도 
클릭시 동일하게 동작하지만 10개중 어느 쪽 상품 5개씩인 부분도 표시됨


3-2-3-3  4개의 아이콘 중  < , > 호버시 변화  
기능:  위 아이콘중  < , >  의 아이콘을 마우스 호버시 아이콘의 테두리가
기존 회색 > 검정색 으로 변경됨 

3-3 121 배치 배너
구성: 총 4개의 배너로 구성되여 있고
양쪽 끝으로 긴 배너 2개와 가운데  긴배너  절반보다 작은 배너 2개가 배치되여있음 
이미지로 구성되여 있으며  긴베너 480x670 중간배너 480x320의 길이를 가짐 

3-3-1 배너 제작1 긴베너

사용가능:
추가기능:

3-3-2 베너 제작2 중간배너

사용가능:
추가기능: 

3-3-3 마우스 호버시 상품명 텍스트 이미지 변경

사용가능:
추가기능:

3-3-4  위 호버된 상품 클릭시 각 상품에 맞는 제품 카테고리리스트로 이동

사용기능:
추가기능:



3-4 가로 중간 베너
구성: 베너인지 아닌지 확실하게 무엇인지 알수 없으나 
텍스트 영역 2개  
클릭시 회원가입으로 연결되는 버튼 1개 
이미지 인데 스크롤에 따라서 보이는면이 달라지는 베너 1로 구성됨

3-4-1 베너영역 설정 및 생성 

사용가능:
추가기능:

3-4-2 베너 스크롤시 보이는면 달라지는 기능 구현 

사용가능:
추가기능:

3-4-3 텍스트 영역 생성
크기: 윗 베너의 크기는 알수 없으나 베너의 2/3 지점에 위치해있으며

1662/424 크기에 
큰텍스트: 1662/49
작은텍스트: 1662/19

사용가능:
추가기능:

3-4-4 텍스트영역 내에 조인 버튼 생성

사용가능:
추가기능:

3-4-5 조인버튼 호버시 내부 텍스트 제외 나머지칸 색꽉참 구현 

사용가능:
추가기능:

3-4-6 조인버튼 호버및 클릭시 회원가입 페이지 링크 

사용가능:
추가기능:

3-5 sonny Angel Regular = 4
구성: 소제목 과 1줄에 4개씩 7줄 총 28개의 상품 들로 구성된
가장 메인 
1) 소제목 
2) 상품 나열 

3-5-1 소제목 만들기 (신상품)
기능:  위에 만들었던 3-2-1 미니타이틀 (추천상품) 와 동일방식

사용가능:
추가기능:

3-5-2 상품나열 
기능: 위 3-2-2  상품 소개와 유사하나 다른점은
*크기는 여기 상품이 더 크다
*자동 상품 이동 이 없다 

사용가능:
추가기능:


3-6 버튼클릭 이동베너 = 3
구성:  950/460의  가운데 메인 이미지와 2/5 정도의  보여지는 이미지가
양쪽에 배치되여있고 메인이미지에 좌우 측에는 이미지 넘김 버튼이있어서
누른위치로 이미지가 전환되며  총 4개의 이미지가 돌아가는 구조

1)이미지 베너 생성 
2) 좌우 이미지베너 이동 버튼 생성
3)이동버튼 기능 구현

3-6-1 이미지 베너 생성 

사용기능: 
추가기능:

3-6-2 좌우 이미지베너 이동 버튼 생성

사용기능:
추가기능:

3-6-3 이동버튼 기능 구현

사용기능:
추가기능:

3-7 이미지배너 = 6
구성: 총 6개로 구성되여 각각의 베너 클릭시 링크가 되여있으며 
배치로는 1열에 2개씩 3열 총 6개 이고 
각각의 링크를 살펴 보면 

1 멤버쉽 , 뉴스&이벤트 탭 내에 계시글 중 첫구매 관련 
2 뉴스&이벤트 , 구입처 지도 
3기부관련이나 관련 페이지는 안보임 ,  카톡선물연결링크 

1) 이미지 베너 생성
2)이미지 배너 호버 시 각각 변경 문구 생성
3) 각각 이미지 배너 마다 링크 설정 

3-7-1 이미지 배너 생성
기능: 765/280 박스에 735/250 크기로 6개가 있음 

사용기능:
추가기능: 

3-7-2 이미지베너 호버 시 각각 변경 문구 생성

사용기능:
추가기능:

3-7-3 이미지 베너 링크 설정
참고: 각각 링크에 대한걸 윗글 참조

사용기능:
추가기능:

3-8 마지막 미니베너 = 22
구성:  인스타그램에 연결된 계시한 사진과 클릭시 계시한 계시물이 팝업으로
뜨고  버튼이 있어 클릭시 바로 인스타그램 계정으로 안내된다

1) 인스타 계정 사진 및  버튼 생성 
2) 버튼 클릭시  인스타  그램 계정 팝업창 생성 연결
3) 인스타 그램 계시물 사진들 블러오기 
4)계시글에 따라 사진상에 아이콘으로 표시 
5)마우스 호버시  이미지 띄우기
6) 계시글 사진 클릭시 팝업창 생성 

3-8-1 인스타계정 사진 및 버튼 생성 
기능:  프로필 이미지 사진 과 그옆 follow  클릭 버튼 생성

사용기능:
추가기능:

3-8-2 팔로우 버튼 클릭시 인스타그램 계정 팝업창 생성

사용기능:
추가기능:

3-8-3 인스타그램 계시물 불러오기 
기능: 계시글을 가져와서 올렸던 글마다 메인사진을
블러와서 보여줘야함
풀사이즈 일시 1열에 11개 2열로 구성되여있고
스크롤이 있어서 아래로 내리면 더보기 가능

사용기능:
추가기능:

3-8-4 계시글에 따라 사진상에 아이콘으로 표시 
기능:  글마다 사진이 여러장인지 동영상인지에 대한
구분을 알려주는아이콘

사용기능:
추가기능:

3-8-5 마우스 호버시 이미지 변경
기능: 1개의 이미지로 동일하게  보임


사용기능:
추가기능:

3-8-6 계시글 사진 클릭시 인스타그램 팝업창 생성 

사용기능:
추가기능:


사이즈에 따라 보여지는 구성 이 달라지는게 트랜스 포머도 아니고 ㅡㅡ

980의 경우
메인베너= 1
bast wish = 3 *
121 배치 배너
가로 중간 베너
4.sonny Angel Regular = 3
자동 이동베너 = 1 (완벽한 1개)
카드형식배너 = 6
마지막 미니베너 = 10 *


4.푸터 
구성:  가장 하단에 위치한 곳으로 크게  4곳의 구역을 가지면서
푸터의 상단 중단 하단 으로 구성되여있고 
푸터의 중단의 경우 안내관련 글들이 위치함 

1) 푸터 상단 
2) 푸터 중단 로고 와 회사 관련정보
3) 푸터 중간 기타 안내
4) 푸터 하단  안내바  

4-1 푸터상단
구성:  구분선 위아래 에 있고 그사이에 텍스트로 된 링크가 있음 

4-1-1 푸터 구분선 및  텍스트 버튼 생성

사용가능:
추후기능:

4-1-2 텍스트버튼 링크 연결

사용가능:
추후기능:

4-2 푸터 중단 로고 와 회사 관련정보
구성:   소니엔젤 타이틀 로고 및 회사 위치 와 같은 텍스트 정보 

4-2-1 푸터 로고 생성 
기능: 이미지  파일 이므로 위치를 잘잡아줘야함

사용가능:
추가기능:

4-2-2  로고 링크하기 
기능: 로고가 링크가되여 클릭시 새로고침인지 메인화면으로 나옴

사용가능:
추가기능:

4-2-3 회사 관련 텍스트 

사용가능:
추가기능:

4-3 푸터 중간 기타안내 
구성:  2열 구성에  1열에 3 개 2열에 2개 총 5개 의 항목으로 구성되며
위에 회사관런 텍스트 같이 여러 안내 가 되여있고  여기는 
각각 다르기 때문에 세분되게 하는게 좋다 

1) 서비스센타 안내
2) 무통장입금 관련 
3) 서비스 안내 
4) 팔로우 관련 (페이스북, 인스타그램)
5)구매안전서비스 관련 

4-3-1 C/S 센터 
구성: 텍스트로 문의와 A/S 관련 센터  정보 기재

사용가능:
추가기능:

4-3-2 무통장입금 안내
구성: 위 4-3-1 과 비슷함  
추가적으로  인터넷뱅킹 관련 안내가 있다

1) 무통장입급 안내 텍스트 생성
2) 인터넷뱅킹 바로가기 버튼생성
3)클릭시  미니창에 각은행 명 생성
4)은행명 클릭시 링크 연결 

4-3-2-1 무통장입금 안내 텍스트 생성

사용가능:
추가기능:

4-3-2-2 인터넷뱅킹바로가기 버튼 생성 

사용가능:
추가기능:

4-3-2-3 클릭시 미니 창에 각은행 명 생성 
기능: 위에서생성된 버튼을 클릭시 창이 뜨면서 
각각의 은행명이 보인다

사용기능:
추가기능:

4-3-2-4 은행명 클릭시 링크 연결  

사용가능:
추가기능:


4-3-3 서비스 
구성: 총 3개의 버튼으로 구성되여 있고 각 버튼마다 링크가 걸려 있다

1) 서비스  버튼 3개 생성
2) 버튼 클릭시 링크 

4-3-3-1 서비스 버튼 3개 생성

사용가능:
추가기능:

4-3-3-2 버튼 클릭시 링크 

사용기능:
추가기능:

4-3-4  페이스북 , 인스타그램  팔로우 안내
구성: 팔로워 안내 와 로고 버튼 클릭시 링크연결

1) 페이스북 , 인스타그램 로고 버튼 생성
2) 버튼 링크 연결

4-3-4-1 페이스북 , 인스타그램 로고 버튼 생성

사용가능:
추가기능:

4-3-4-2 버튼링크연결

사용기능:
추가기능:

4-3-5  구매안전서비스 가입사실 확인 
구성:  안내 텍스트 및 위 서비스 가입사실 안내 버튼 클릭시 링크

1) 제목 및  안내 텍스트 생성
2) 서비스 가입사실 확인 버튼 생성
3)위 버튼 링크 연결 

4-3-5-1 제목 및 안내 텍스트 생성

사용기능:
추가기능:

4-3-5-2 서비스 가입사실 버튼 생성 

사용기능:
추가기능:

4-3-5-3  가입사실버튼 클릭시 링크 

사용기능:
추가기능:

4-4  푸터 하단 안내바 
구성:  내가 만들어본게 아니래서 설명은 못하겠지만 그냥 하단 바인듯..

1) 하단 안내바 생성 
2) 텍스트 삽입 
3) 하단바 컨텐츠 색상 입히기

4-4-1 하단바 생성

사용기능:
추가기능:

4-4-2 텍스트 삽입

사용기능:
추가기능:

4-4-3 하단바 컨텐츠 색상 입히기

사용기능:
추가기능:


공통: 기본 클릭할수 있는건 기본 마우스포인터 에서 손모양으로 변경됨
* 푸터의  4-3-2 무통장입금 안내 의 버튼 과 버튼클릭수 선택에서도 마우스 변화 없음

**Comment by nmj8585** [comment]
상품 소개 페이지  - Regular Refine

1. 헤더 
구성: 기존 홈페이지의 구성과 같다 
변동사항 없음 

2. 사이드메뉴
구성: 기존 홈페이지의 구성과 같다
변동사항 없음 
3. 컨텐츠


내일하자 으으으 ㅠ



4. 푸터
구성: 기존 홈페이지의 구성과 같다 
변동사항 없음
